language: node_js
node_js:
  - "6"
cache: yarn
install:
  - yarn install

jobs:
  include:
    - stage: test
      script:
        - yarn run test
    - stage: lint
      script:
        - yarn run lint
