name: SVGI Inclusive Language

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "npm"
      - name: woke
        uses: get-woke/woke-action@v0
        with:
          fail-on-error: true
      - name: Run AlexJS
        run: npx alex@10.0.0 README.md
